#!name=BankRules

#!desc=将银行域名设置成直连访问

[Rule]
#!CN


#!HK
#!HSBC
DOMAIN-SUFFIX,hsbc.com.hk,DIRECT
#!CCBA
DOMAIN-SUFFIX,asia.ccb.com,DIRECT
#!BOCHK
DOMAIN-SUFFIX,bochk.com,DIRECT
DOMAIN-SUFFIX,etnet.com.hk,DIRECT
#!DBSHK
DOMAIN-SUFFIX,dbs.com.hk,DIRECT
#!CNCBI
DOMAIN-SUFFIX,cncbinternational.com,DIRECT
#!CMBWL
DOMAIN-SUFFIX,cmbwinglungbank.com,DIRECT
#!HSB
DOMAIN-SUFFIX,hangseng.com,DIRECT
#!NCB
DOMAIN-SUFFIX,ncb.com.hk,DIRECT
#!ICBCA
DOMAIN-SUFFIX,icbcasia.com,DIRECT
#!ZA
DOMAIN-SUFFIX,za.group,DIRECT
#!LIVI
DOMAIN-SUFFIX,livibank.com,DIRECT
#!WELAB
DOMAIN-SUFFIX,welab.bank,DIRECT
#!FUSION
DOMAIN-SUFFIX,fusionbank.com,DIRECT
#!PAOB
DOMAIN-SUFFIX,paob.com.hk,DIRECT
#!ANTBANK
DOMAIN-SUFFIX,antbank.hk,DIRECT
#!AIRSTAR
DOMAIN-SUFFIX,airstarbank.com,DIRECT

#!UK
DOMAIN-SUFFIX,barclays.co.uk,DIRECT
DOMAIN-SUFFIX,aquacard.co.uk,DIRECT
DOMAIN-SUFFIX,hsbc.co.uk,DIRECT
DOMAIN-SUFFIX,lloydsbank.com,DIRECT
DOMAIN-SUFFIX,santander.co.uk,DIRECT
DOMAIN-SUFFIX,bankofscotland.co.uk,DIRECT
DOMAIN-SUFFIX,natwest.com,DIRECT
DOMAIN-SUFFIX,halifax.co.uk,DIRECT
DOMAIN-SUFFIX,newdaycards.com,DIRECT
DOMAIN-SUFFIX,totallymoney.com,DIRECT
DOMAIN-SUFFIX,chase.co.uk,DIRECT